# Exploration Notebook
This is a placeholder notebook for Bronze layer.

# Importing the Neccessary Modules

In [3]:
import pandas as pd
import importlib.util
import sys
import os
import warnings
warnings.filterwarnings('ignore')

# Imoprting the neccessary File Modules
Using importlib.utils to add paths dynamically to import the neccessary modules

In [4]:
# Define paths to all required modules
module_paths = {
    'file_path_for_load_raw_data': "../../src/data/load_raw_data.py",
    'file_path_for_save': "../../src/data/save_cleaned_data.py",
    'file_path_for_clean': "../../src/data/clean_data.py"
}

# Dynamically import all modules
loaded_modules = {}
for name, path in module_paths.items():
    spec = importlib.util.spec_from_file_location(f'src.{name}', path)
    if spec is None:
        raise ImportError(f'Could not load module from {path}')
    module = importlib.util.module_from_spec(spec)
    sys.modules[f'src.{name}'] = module
    spec.loader.exec_module(module)
    loaded_modules[name] = module

# Assign readable aliases
load_module = loaded_modules['file_path_for_load_raw_data']
clean_module = loaded_modules['file_path_for_clean']
save_module = loaded_modules['file_path_for_save']

print('All modules loaded successfully!')
print("Added the module path for loading Raw data, Saving data, and Cleaning data...")

All modules loaded successfully!
Added the module path for loading Raw data, Saving data, and Cleaning data...

# Loading the Dataset
Importing the Raw Data

In [5]:
# Usage of Load Data module
loaded_data = load_module.LoadData()
print("Data loaded successfully using LoadData module")

Raw data loaded successfully!
Data loaded successfully using LoadData module

In [6]:
retention = loaded_data.retention
bob = loaded_data.bob

print("Data Loaded Successfully...")

Data Loaded Successfully...

### Display data info and first few rows before Cleaning

In [7]:
print("retention - Data Info:")
print("Info: \n", retention.info())
print(f"Shape: {retention.shape}")
print(f"Null counts:\n{retention.isnull().sum()}")
print(f"First 5 rows:")
display(retention.head())

print("\nbob - Data Info:")
print("Info: \n", bob.info())
print(f"Shape: {bob.shape}")
print(f"Null counts:\n{bob.isnull().sum()}")
print(f"First 5 rows:")
display(bob.head())

retention - Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 85411 entries, 0 to 85410
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Case ID                    85411 non-null  str
 1   Case Title                 85411 non-null  str
 2   Country                    85411 non-null  str
 3   Pull VAN                   85411 non-null  float64
 4   New VAN                    85411 non-null  float64
 5   VAN                        84980 non-null  float64
 6   Number of Contracts        71249 non-null  float64
 7   Machines                   71249 non-null  float64
 8   Branch                     77280 non-null  str
 9   Customer Account Number    77949 non-null  str
 10  Customer Name              77949 non-null  str
 11  Customer Since             0 non-null      float64
 12  Agreement End Date         85205 non-null  str
 13  Pull Type                  50204 non-null  str
 14  Case Type                  85411 non-null  str
 15  Risk                       40027 non-null  str
 16  Current Status             85411 non-null  str
 17  Resolution Status          85411 non-null  str
 18  Number Of Repair Cases     62102 non-null  float64
 19  Number of OverdueServices  62102 non-null  float64
 20  CompanySize                61812 non-null  str
 21  Customer Tier              54447 non-null  str
 22  Case Origin                64221 non-null  str
 23  Case Creation Date         85411 non-null  str
 24  Resolved Time              71893 non-null  str
 25  Registered Time            85411 non-null  str
 26  Resolved Date              71893 non-null  str
 27  Registered Date            85411 non-null  str
 28  Expected Pull Date         85111 non-null  str
dtypes: float64(8), str(21)
memory usage: 18.9 MB
Info:
 None
Shape: (85411, 29)
Null counts:
Case ID                          0
Case Title                       0
Country                          0
Pull VAN                         0
New VAN                          0
VAN                            431
Number of Contracts          14162
Machines                     14162
Branch                        8131
Customer Account Number       7462
Customer Name                 7462
Customer Since               85411
Agreement End Date             206
Pull Type                    35207
Case Type                        0
Risk                         45384
Current Status                   0
Resolution Status                0
Number Of Repair Cases       23309
Number of OverdueServices    23309
CompanySize                  23599
Customer Tier                30964
Case Origin                  21190
Case Creation Date               0
Resolved Time                13518
Registered Time                  0
Resolved Date                13518
Registered Date                  0
Expected Pull Date             300
dtype: int64
First 5 rows:

,Case ID,Case Title,Country,Pull VAN,New VAN,VAN,Number of Contracts,Machines,Branch,Customer Account Number,...,Number of OverdueServices,CompanySize,Customer Tier,Case Origin,Case Creation Date,Resolved Time,Registered Time,Resolved Date,Registered Date,Expected Pull Date
0,CAS-32058-P6H2Z7,Service Claim,United Kingdom,0.0,0.0,0.00,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:05,NaN,17:00:00,NaN,23-07-2025,29-Jun-26
1,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,423.00,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
2,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,352.50,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
3,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1769.76,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27
4,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1474.80,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27

bob - Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 376803 entries, 0 to 376802
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   account_number        376784 non-null  str
 1   company_sizing        374120 non-null  str
 2   postal_code           376782 non-null  str
 3   branch                376784 non-null  str
 4   vat_number            376388 non-null  str
 5   agreement_number      376784 non-null  str
 6   agreement_start_date  376784 non-null  str
 7   agreement_end_date    376784 non-null  str
 8   renewal_type          376784 non-null  str
 9   agreement_type        376784 non-null  str
 10  line_of_business      376784 non-null  str
 11  system_status         376784 non-null  str
 12  product_bob           376793 non-null  float64
 13  fee_bob               376793 non-null  float64
 14  total_bob             376793 non-null  float64
 15  is_bob                376784 non-null  str
 16  bpg                   373360 non-null  str
 17  msdyn_product_number  374539 non-null  str
 18  product_name          374539 non-null  str
 19  service_interval      304783 non-null  float64
 20  unit_amount           373509 non-null  float64
 21  billing_interval      359062 non-null  float64
 22  billing_period        359062 non-null  str
 23  machine               180335 non-null  str
 24  machine_variant       180344 non-null  str
 25  chemistry             138048 non-null  str
dtypes: float64(6), str(20)
memory usage: 74.7 MB
Info:
 None
Shape: (376803, 26)
Null counts:
account_number              19
company_sizing            2683
postal_code                 21
branch                      19
vat_number                 415
agreement_number            19
agreement_start_date        19
agreement_end_date          19
renewal_type                19
agreement_type              19
line_of_business            19
system_status               19
product_bob                 10
fee_bob                     10
total_bob                   10
is_bob                      19
bpg                       3443
msdyn_product_number      2264
product_name              2264
service_interval         72020
unit_amount               3294
billing_interval         17741
billing_period           17741
machine                 196468
machine_variant         196459
chemistry               238755
dtype: int64
First 5 rows:

,account_number,company_sizing,postal_code,branch,vat_number,agreement_number,agreement_start_date,agreement_end_date,renewal_type,agreement_type,...,bpg,msdyn_product_number,product_name,service_interval,unit_amount,billing_interval,billing_period,machine,machine_variant,chemistry
0,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-327311,17-03-2025 00:00,16-03-2026 00:00,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK400EAA-001483-001,SK400 EAA + 400L of KLEEN7960S + Waste Rustpro...,1.0,9812.14,1.0,monthly,SK400,AA,KLEEN7960S
1,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332280,14-04-2025 00:00,13-04-2028 00:00,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
2,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332282,14-04-2025 00:00,13-04-2028 00:00,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
3,UK02-CGBA124601-L,20-49,BT71 7ET,Lisburn,GB714768220,GBC4000950-Auto waste,24-06-2022 00:00,23-06-2026 00:00,Automatic Renewal,Scheduled Billing,...,40. Oil Filters,K0000-040259-000,Waste Paint Sludge Collection - 205,0.0,7686.88,1.0,monthly,NaN,NaN,NaN
4,UK02-CGBA034502-L,50-99,BT41 3UF,Lisburn,Unknown,GBC3028394-Chemistry,04-11-2024 00:00,03-11-2025 00:00,Automatic Renewal,Scheduled Billing,...,30. Allied Products,C0000-000468-001,Delivery of Std Thinners - 205Ltrs (6),1.0,6933.91,1.0,monthly,NaN,NaN,NaN

In [15]:
# retention.nunique()
bob.nunique()

account_number          23772
branch                     19
agreement_number        29618
agreement_start_date     2812
agreement_end_date       1201
agreement_type              2
system_status               4
product_bob             34122
fee_bob                  5596
total_bob               50095
is_bob                      2
unit_amount             29708
msdyn_product_number     6407
product_name              673
dtype: int64

### Dropping the Unneccessary Features

In [8]:
# useful features of bob
bob_key_cols = ['account_number', 'branch', 'agreement_number', 'agreement_start_date', 'agreement_end_date', 'agreement_type', 'system_status', 'product_bob', 'fee_bob', 'total_bob', 'is_bob', 'unit_amount', 'msdyn_product_number', 'product_name']

bob = bob[bob_key_cols]
bob.info()
bob.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 376803 entries, 0 to 376802
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   account_number        376784 non-null  str
 1   branch                376784 non-null  str
 2   agreement_number      376784 non-null  str
 3   agreement_start_date  376784 non-null  str
 4   agreement_end_date    376784 non-null  str
 5   agreement_type        376784 non-null  str
 6   system_status         376784 non-null  str
 7   product_bob           376793 non-null  float64
 8   fee_bob               376793 non-null  float64
 9   total_bob             376793 non-null  float64
 10  is_bob                376784 non-null  str
 11  unit_amount           373509 non-null  float64
 12  msdyn_product_number  374539 non-null  str
 13  product_name          374539 non-null  str
dtypes: float64(4), str(10)
memory usage: 40.2 MB

account_number            19
branch                    19
agreement_number          19
agreement_start_date      19
agreement_end_date        19
agreement_type            19
system_status             19
product_bob               10
fee_bob                   10
total_bob                 10
is_bob                    19
unit_amount             3294
msdyn_product_number    2264
product_name            2264
dtype: int64

In [9]:
# useful features of Retention
retention_key_cols = ['Customer Account Number', 'Case Type', 'Current Status', 'Resolution Status']

retention = retention[retention_key_cols]
retention.info()
retention.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 85411 entries, 0 to 85410
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Customer Account Number  77949 non-null  str
 1   Case Type                85411 non-null  str
 2   Current Status           85411 non-null  str
 3   Resolution Status        85411 non-null  str
dtypes: str(4)
memory usage: 2.6 MB

Customer Account Number    7462
Case Type                     0
Current Status                0
Resolution Status             0
dtype: int64

## Data Cleaning

Applying the CleanData class to standardize column names, remove duplicates, and handle missing values.

In [10]:
# STEP 2: Data Cleaning
print("STEP 2: Data Cleaning")

# Initialize CleanData
cleaning_Data = clean_module.CleanData(retention, bob)

# Converting the name of the features to the snake_case method
retention_cleaned= cleaning_Data.columns_to_snake_case(retention)
bob_cleaned = cleaning_Data.columns_to_snake_case(bob)

# Dropping the duplicate values
retention_cleaned = cleaning_Data.dropping_duplicates(retention_cleaned)
bob_cleaned = cleaning_Data.dropping_duplicates(bob_cleaned)

# Filling Numerical Null values 
retention_cleaned = cleaning_Data.dropping_nulls(retention_cleaned)
bob_cleaned = cleaning_Data.dropping_nulls_subset(bob_cleaned, ['account_number'])

# Hnadling the Date columns 
bob_cleaned = cleaning_Data.handling_date_datatypes(bob_cleaned, ['agreement_start_date', 'agreement_end_date'])

print("\nCleaning complete!")

print(f"\nRetention cleaned shape: {retention_cleaned.shape}")
print(f"BoB cleaned shape: {bob_cleaned.shape}")

print(f"\nRetention columns: {retention_cleaned.columns.tolist()}")
print(f"BoB columns: {bob_cleaned.columns.tolist()}")

print("\nRetention Info:")
print(retention_cleaned.info())
print(retention_cleaned.duplicated().sum())
print(retention_cleaned.isnull().sum())

print("\nBoB Info:")
print(bob_cleaned.info())
print(bob_cleaned.duplicated().sum())
print(bob_cleaned.isnull().sum())

STEP 2: Data Cleaning
Data loaded successfully in CleanData class!

Cleaning complete!

Retention cleaned shape: (35286, 4)
BoB cleaned shape: (171665, 14)

Retention columns: ['customer_account_number', 'case_type', 'current_status', 'resolution_status']
BoB columns: ['account_number', 'branch', 'agreement_number', 'agreement_start_date', 'agreement_end_date', 'agreement_type', 'system_status', 'product_bob', 'fee_bob', 'total_bob', 'is_bob', 'unit_amount', 'msdyn_product_number', 'product_name']

Retention Info:
<class 'pandas.DataFrame'>
Index: 35286 entries, 3000 to 85408
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_account_number  35286 non-null  str
 1   case_type                35286 non-null  str
 2   current_status           35286 non-null  str
 3   resolution_status        35286 non-null  str
dtypes: str(4)
memory usage: 1.3 MB
None
0
customer_account_number    0
case_type                  0
current_status             0
resolution_status          0
dtype: int64

BoB Info:
<class 'pandas.DataFrame'>
Index: 171665 entries, 0 to 376788
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   account_number        171665 non-null  str
 1   branch                171665 non-null  str
 2   agreement_number      171665 non-null  str
 3   agreement_start_date  171665 non-null  datetime64[us]
 4   agreement_end_date    171665 non-null  datetime64[us]
 5   agreement_type        171665 non-null  str
 6   system_status         171665 non-null  str
 7   product_bob           171665 non-null  float64
 8   fee_bob               171665 non-null  float64
 9   total_bob             171665 non-null  float64
 10  is_bob                171665 non-null  str
 11  unit_amount           169283 non-null  float64
 12  msdyn_product_number  170422 non-null  str
 13  product_name          170422 non-null  str
dtypes: datetime64[us](2), float64(4), str(8)
memory usage: 19.6 MB
None
0
account_number             0
branch                     0
agreement_number           0
agreement_start_date       0
agreement_end_date         0
agreement_type             0
system_status              0
product_bob                0
fee_bob                    0
total_bob                  0
is_bob                     0
unit_amount             2382
msdyn_product_number    1243
product_name            1243
dtype: int64

In [11]:
display(retention_cleaned)
print(retention_cleaned.isnull().sum())
display(bob_cleaned)
print(bob_cleaned.isnull().sum())

      customer_account_number     case_type current_status   resolution_status
3000        UK02-CGBA121453-L          Risk    In Progress  OPEN - In Progress
3005        UK02-CGBA027133-L          Risk    In Progress  OPEN - In Progress
3007        UK02-SGBA028701-L          Risk    In Progress  OPEN - In Progress
3009        UK02-CGBA210070-L          Risk    In Progress  OPEN - In Progress
3011        UK02-CGBA212953-L          Risk    In Progress  OPEN - In Progress
...                       ...           ...            ...                 ...
85398       UK02-CGBA113854-L  Cancellation  Pull Complete       Customer Lost
85400       UK02-CGBA107591-L  Cancellation  Pull Complete       Customer Lost
85404       UK02-CGBA010154-L  Cancellation  Pull Complete       Customer Lost
85406       UK02-CGBA010113-L  Cancellation  Pull Complete       Customer Lost
85408       UK02-CGBA007194-L  Cancellation  Pull Complete       Customer Lost

[35286 rows x 4 columns]

customer_account_number    0
case_type                  0
current_status             0
resolution_status          0
dtype: int64

,account_number,branch,agreement_number,agreement_start_date,agreement_end_date,agreement_type,system_status,product_bob,fee_bob,total_bob,is_bob,unit_amount,msdyn_product_number,product_name
0,UK02-CGBA029544-L,Elmswell,GBC4019041-Machine Services-327311,2025-03-17,2026-03-16,Scheduled Billing,Active,117745.68,0.00,117745.68,Yes,9812.14,ISK400EAA-001483-001,SK400 EAA + 400L of KLEEN7960S + Waste Rustpro...
1,UK02-CGBA029544-L,Elmswell,GBC4021962-Machine Services-332280,2025-04-14,2028-04-13,Scheduled Billing,Active,105967.68,0.00,105967.68,Yes,8830.64,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...
2,UK02-CGBA029544-L,Elmswell,GBC4021962-Machine Services-332282,2025-04-14,2028-04-13,Scheduled Billing,Active,105967.68,0.00,105967.68,Yes,8830.64,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...
3,UK02-CGBA124601-L,Lisburn,GBC4000950-Auto waste,2022-06-24,2026-06-23,Scheduled Billing,Active,92242.56,0.00,92242.56,Yes,7686.88,K0000-040259-000,Waste Paint Sludge Collection - 205
4,UK02-CGBA034502-L,Lisburn,GBC3028394-Chemistry,2024-11-04,2025-11-03,Scheduled Billing,Active,83206.92,0.00,83206.92,Yes,6933.91,C0000-000468-001,Delivery of Std Thinners - 205Ltrs (6)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376770,UK02-SGBA033465-L,Montrose,GBN033465-Machine Services-107007,2018-01-01,2027-01-01,PATOS,Active,1398.90,22.56,1421.46,Yes,699.45,IM170BAA-001030027,M170 BAA + 22L of SOLV300 + Waste Solvent
376771,UK02-SGBA033473-L,Montrose,GBN033473-Machine Services-111847,2018-01-01,2027-01-01,PATOS,Active,2218.24,33.10,2251.34,Yes,1109.12,IM300BAA-001221027,M300 BAA + 45L of SOLV300 + Waste Solvent
376780,UK02-SGBA033582-L,Montrose,GBN033582-Machine Services-104522,2018-01-01,2027-01-01,PATOS,Active,259.39,9.71,269.10,Yes,259.39,IC500XAA-001694053,C500 + 22L of SOLV300 + Waste Solvent
376785,UK02-SGBA033779-L,Stirling,GBN033779-Machine Services-104182,2018-01-01,2027-01-01,PATOS,Active,625.04,32.50,657.54,Yes,312.52,IC500XAA-001694027,C500 + 22L of SOLV300 + Waste Solvent
376788,UK02-SGBA110203-L,Montrose,GBN033874-Machine Services-106942,2018-01-01,2027-01-01,PATOS,Active,1441.40,29.05,1470.45,Yes,720.70,IM170BAA-001030027,M170 BAA + 22L of SOLV300 + Waste Solvent

account_number             0
branch                     0
agreement_number           0
agreement_start_date       0
agreement_end_date         0
agreement_type             0
system_status              0
product_bob                0
fee_bob                    0
total_bob                  0
is_bob                     0
unit_amount             2382
msdyn_product_number    1243
product_name            1243
dtype: int64

# Saving the Cleaned Data in data/02_Intermediate

In [12]:
# usage of Save Data module
saving_data = save_module.StoreData(retention_cleaned, bob_cleaned)
saving_data.save_data()

Data saved successfully to the intermediate data folder!